version: 2
project_name: a
builds:
  - binary: a
    env:
      - CGO_ENABLED=0
    id: linux
    main: ./cmd/a
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - "baton_lambda_support"
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/conductorone/a:{{ .Version }}-amd64"
      - "ghcr.io/conductorone/a:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/conductorone/a:{{ .Version }}-arm64"
      - "ghcr.io/conductorone/a:latest-arm64"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile.lambda
    image_templates:
      - "168442440833.dkr.ecr.us-west-2.amazonaws.com/a:{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: ghcr.io/conductorone/a:{{ .Version }}
    image_templates:
      - ghcr.io/conductorone/a:{{ .Version }}-amd64
      - ghcr.io/conductorone/a:{{ .Version }}-arm64
  - name_template: ghcr.io/conductorone/a:latest
    image_templates:
      - ghcr.io/conductorone/a:latest-amd64
      - ghcr.io/conductorone/a:latest-arm64
checksum:
  disable: true
release:
  disable: true
changelog:
  disable: true
