name: Dispatch Metadata

on:
  release:
    types: [published]

jobs:
  dispatch:
    uses: TRAINFACED/b/.github/workflows/on-tag.yml@main
    with:
        tag: ${{ github.ref_name }}
    secrets:
        METADATA_PAT: ${{ secrets.METADATA_PAT }}
