name: Dispatch Metadata

on:
  push:
    tags:
      - 'v*'

jobs:
  dispatch:
    uses: TRAINFACED/b/.github/workflows/relay-to-metadata.yml@main
    with:
      tag: ${{ github.ref_name }}
    secrets:
      METADATA_PAT: ${{ secrets.METADATA_PAT }}